/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MibParsePanel.java
 *
 * Created on 2011-5-23, 11:46:19
 */
package jetsennet.jbmp.ui.util;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;

import org.apache.log4j.Logger;

import jetsennet.jbmp.entity.SnmpNodesEntity;
import jetsennet.jbmp.mib.parse.MibLoader;
import jetsennet.jbmp.mib.parse.MibLoaderHelper;
import jetsennet.jbmp.mib.parse.MibLoaderUtil;
import jetsennet.jbmp.util.FileUtil;

/**
 * @author Guo
 */
public class MibParsePanel extends javax.swing.JPanel
{

    private SnmpTableTableModel model;
    private DefaultComboBoxModel tModel;
    private MibLoaderHelper helper;
    private DefaultMutableTreeNode root;
    private static final Logger logger = Logger.getLogger(MibParsePanel.class);

    /** Creates new form MibParseP.anel */
    public MibParsePanel()
    {
        this.before();
        initComponents();
    }

    private void before()
    {
        root = new DefaultMutableTreeNode();
        model = new SnmpTableTableModel(null);
        tModel = new DefaultComboBoxModel();
        this.modifyComboBox();
    }

    private void modifyComboBox()
    {
        tModel.removeAllElements();
        tModel.addElement("请选择");
        // ArrayList<String> types = modao.getTypes();
        // for (String type : types)
        // {
        // tModel.addElement(type);
        // }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    private void initComponents()
    {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fileField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fileButton = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox();
        readButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        oidTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        snmpTree = new javax.swing.JTree(root);
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        snmpNodeName = new javax.swing.JTextField();
        snmpNodeOid = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        snmpNodeDesc = new javax.swing.JTextArea();
        snmpNodeFile = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        scanIpAddr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        scanPort = new javax.swing.JTextField();
        scanCommunity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        scanResult = new javax.swing.JList();

        jLabel4.setText("jLabel4");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "源"));

        jLabel1.setText("文件：");

        jLabel2.setText("类型：");

        saveButton.setText("保存");
        saveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("类型：");

        fileButton.setText("加载");
        fileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fileButtonActionPerformed(evt);
            }
        });

        typeComboBox.setModel(tModel);
        typeComboBox.setSelectedIndex(0);

        readButton.setText("读取");
        readButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                readButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("刷新");
        refreshButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                refreshButtonActionPerformed(evt);
            }
        });

        delButton.setText("删除");
        delButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                delButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                    jPanel1Layout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeComboBox, 0, 581, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton).addGap(6, 6, 6).addComponent(refreshButton)).addGroup(
                    jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileField, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)).addGroup(
                    jPanel1Layout.createSequentialGroup().addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeField, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE))).addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(fileButton).addComponent(saveButton))
                    .addComponent(readButton)).addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(fileField,
                    javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileButton)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(typeField,
                    javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(typeComboBox,
                    javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readButton).addComponent(refreshButton).addComponent(delButton)).addContainerGap(
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        oidTable.setModel(model);
        jScrollPane1.setViewportView(oidTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1,
            javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1,
            javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE));

        jTabbedPane1.addTab("节点", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout
            .setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 851, Short.MAX_VALUE));
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 426, Short.MAX_VALUE));

        jTabbedPane1.addTab("类型定义", jPanel4);

        jSplitPane1.setDividerLocation(300);

        snmpTree.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                snmpTreeMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(snmpTree);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            jPanel5Layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 279,
                Short.MAX_VALUE).addContainerGap()));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            jPanel5Layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 404,
                Short.MAX_VALUE).addContainerGap()));

        jSplitPane1.setLeftComponent(jPanel5);

        jLabel5.setText("名称：");

        jLabel6.setText("OID：");

        jLabel7.setText("文件：");

        snmpNodeDesc.setColumns(20);
        snmpNodeDesc.setRows(5);
        jScrollPane3.setViewportView(snmpNodeDesc);

        jLabel12.setText("描述：");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            jPanel7Layout.createSequentialGroup().addContainerGap().addGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                    jPanel7Layout.createSequentialGroup().addComponent(jLabel5).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(snmpNodeName, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)).addGroup(
                    jPanel7Layout.createSequentialGroup().addComponent(jLabel6).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(snmpNodeOid, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)).addGroup(
                    jPanel7Layout.createSequentialGroup().addGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel7).addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
                            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane3,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE).addComponent(snmpNodeFile,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)))).addContainerGap()));

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { jLabel12, jLabel5, jLabel6, jLabel7 });

        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            jPanel7Layout.createSequentialGroup().addGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                    jPanel7Layout.createSequentialGroup().addContainerGap().addGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5).addComponent(
                            snmpNodeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6).addComponent(snmpNodeOid,
                            javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel7).addComponent(
                                snmpNodeFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)).addGroup(
                    jPanel7Layout.createSequentialGroup().addGap(91, 91, 91).addComponent(jLabel12))).addContainerGap()));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("扫描结果"));

        jLabel8.setText("IP地址：");

        jLabel9.setText("端口号：");

        jLabel10.setText("COMMUNITY：");

        jButton1.setText("WALK");

        jLabel11.setText("结果：");

        scanResult.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize()
            {
                return strings.length;
            }

            public Object getElementAt(int i)
            {
                return strings[i];
            }
        });
        jScrollPane4.setViewportView(scanResult);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            jPanel8Layout.createSequentialGroup().addContainerGap().addGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                    jPanel8Layout.createSequentialGroup().addComponent(jLabel8).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scanIpAddr, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)).addGroup(
                    jPanel8Layout.createSequentialGroup().addComponent(jLabel9).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scanPort, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE).addPreferredGap(
                            javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel10).addPreferredGap(
                            javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(scanCommunity, javax.swing.GroupLayout.DEFAULT_SIZE,
                            175, Short.MAX_VALUE)).addGroup(
                    javax.swing.GroupLayout.Alignment.TRAILING,
                    jPanel8Layout.createSequentialGroup().addComponent(jLabel11).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE).addPreferredGap(
                            javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton1))).addContainerGap()));

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { jLabel10, jLabel11, jLabel8, jLabel9 });

        jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            jPanel8Layout.createSequentialGroup().addContainerGap().addGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel8).addComponent(scanIpAddr,
                    javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                    jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel9).addComponent(jLabel10)
                        .addComponent(scanPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(scanCommunity, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                    jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel11,
                        javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE).addComponent(jButton1)).addContainerGap()));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            javax.swing.GroupLayout.Alignment.TRAILING,
            jPanel6Layout.createSequentialGroup().addContainerGap().addGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jPanel8,
                    javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE).addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap()));
        jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            jPanel6Layout.createSequentialGroup().addContainerGap().addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGap(18, 18, 18).addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));

        jSplitPane1.setRightComponent(jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSplitPane1,
            javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSplitPane1,
            javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE));

        jTabbedPane1.addTab("树状图", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup().addContainerGap().addGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jTabbedPane1,
                    javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE).addComponent(jPanel1,
                    javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout.createSequentialGroup().addContainerGap().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455,
                Short.MAX_VALUE).addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt)
    {

        JFileChooser chooser = new JFileChooser(MibLoaderUtil.getMibDirPath());
        chooser.setDialogTitle("MIB文件加载");
        chooser.setMultiSelectionEnabled(true);
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            File[] files = chooser.getSelectedFiles();
            if (files != null && files.length > 0)
            {
                fileButton.setEnabled(false);
                Thread t = new Thread(new MibLoaderRunnable(files));
                t.start();
            }
        }
    }// GEN-LAST:event_fileButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        saveButton.setEnabled(false);
        String type = typeField.getText();
        MibLoader.getInstance().update(helper, Integer.valueOf(type));
        SwingUtilities.invokeLater(new Runnable()
        {

            @Override
            public void run()
            {
                model.fireTableDataChanged();
                saveButton.setEnabled(true);
                modifyComboBox();
            }
        });
    }// GEN-LAST:event_saveButtonActionPerformed

    private void readButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        try
        {
            String selected = (String) tModel.getSelectedItem();
            if ("请选择".equals(selected))
            {
                model.clear();
                return;
            }
            // model.modify(modao.getByType(selected));
        }
        catch (Exception ex)
        {
            logger.error("", ex);
        }
    }// GEN-LAST:event_readButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        this.modifyComboBox();
    }// GEN-LAST:event_refreshButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        String selected = (String) tModel.getSelectedItem();
        if ("请选择".equals(selected))
        {
            return;
        }
        // MibLoader.getInstance().delete(selected);
        this.modifyComboBox();
    }// GEN-LAST:event_delButtonActionPerformed

    private void snmpTreeMousePressed(java.awt.event.MouseEvent evt)// GEN-FIRST:event_snmpTreeMousePressed
    {
        Object obj = snmpTree.getLastSelectedPathComponent();
        if (obj != null)
        {
            DefaultMutableTreeNode dmt = (DefaultMutableTreeNode) obj;
            obj = dmt.getUserObject();
            if (obj != null && obj instanceof SnmpNodesEntity)
            {
                SnmpNodesEntity node = (SnmpNodesEntity) obj;
                snmpNodeName.setText(node.getNodeName());
                snmpNodeOid.setText(node.getNodeOid());
                snmpNodeDesc.setText(node.getNodeDesc());
                snmpNodeFile.setText(node.getMibFile());
            }
        }
    }// GEN-LAST:event_snmpTreeMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delButton;
    private javax.swing.JButton fileButton;
    private javax.swing.JTextField fileField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable oidTable;
    private javax.swing.JButton readButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField scanCommunity;
    private javax.swing.JTextField scanIpAddr;
    private javax.swing.JTextField scanPort;
    private javax.swing.JList scanResult;
    private javax.swing.JTextArea snmpNodeDesc;
    private javax.swing.JTextField snmpNodeFile;
    private javax.swing.JTextField snmpNodeName;
    private javax.swing.JTextField snmpNodeOid;
    private javax.swing.JTree snmpTree;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JTextField typeField;

    /**
     * @param args 参数
     */
    public static void main(String[] args)
    {
        SwingUtilities.invokeLater(new Runnable()
        {

            public void run()
            {
                JFrame frame = new JFrame();
                frame.setContentPane(new MibParsePanel());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // End of variables declaration//GEN-END:variables

    class MibLoaderRunnable implements Runnable
    {

        private File[] files;

        public MibLoaderRunnable(File[] files)
        {
            this.files = files;
        }

        @Override
        public void run()
        {
            MibLoader loader = MibLoader.getInstance();
            helper = loader.load(files);
            final ArrayList<SnmpNodesEntity> mos = helper.getOids();
            SwingUtilities.invokeLater(new Runnable()
            {

                @Override
                public void run()
                {
                    model.modify(mos);
                    builderTree(mos);
                    fileButton.setEnabled(true);
                    fileField.setText(FileUtil.fileList(files));
                }
            });
        }

        private void builderTree(ArrayList<SnmpNodesEntity> nodes)
        {
            root.removeAllChildren();
            if (nodes == null || nodes.isEmpty())
            {
                return;
            }
            Map<String, DefaultMutableTreeNode> temp = new HashMap<String, DefaultMutableTreeNode>();
            for (SnmpNodesEntity node : nodes)
            {
                DefaultMutableTreeNode tNode = new DefaultMutableTreeNode(node);
                SnmpNodesEntity parent = node.getParent();
                if (parent == null)
                {
                    root.add(tNode);
                    temp.put(node.getNodeOid(), tNode);
                }
                else
                {
                    DefaultMutableTreeNode parentNode = temp.get(parent.getNodeOid());
                    if (parentNode != null)
                    {
                        parentNode.add(tNode);
                        temp.put(node.getNodeOid(), tNode);
                    }
                }
            }
            snmpTree.updateUI();
        }
    }

}
