#!/bin/bash
export CLASSPATH='.:./classes:/tools/tomcat/webapps/jbmp/WEB-INF/lib/activation-1.1.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/annotations-api-6.0.35.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/asm-4.2.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/atmosphere-compat-jbossweb-2.0.1.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/atmosphere-compat-tomcat-2.0.1.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/atmosphere-compat-weblogic-0.7.2.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/atmosphere-ping-0.7.2.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/atmosphere-runtime-0.7.2.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/bfss-1.0.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/catalina-6.0.35.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/cglib-3.1.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/commons-codec-1.5.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/commons-dbcp-1.4.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/commons-fileupload-1.3.1.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/commons-io-2.2.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/commons-lang-2.6.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/commons-pool-1.5.4.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/coyote-6.0.35.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/dom4j-1.6.1.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/ehcache-2.8.1.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/integration-cpr-2.0.0.RC4.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/javax.mail-api-1.5.1.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/jaxen-1.1.4.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/jdom-1.1.3.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/jgroups-2.12.3.Final.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/jrobin-1.5.9.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/json-simple-1.1.1.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/juli-6.0.35.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/jxl-2.6.12.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/lib4jnmp-0.0.1-SNAPSHOT.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/log4j-1.2.17.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/mibble_20110105-1.0.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/mvel2-2.1.9.Final.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/mysql-connector-java-5.1.29.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/ojdbc-14.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/org.apache.commons.lang-2.6.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/parse-1.0.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/poi-3.10-FINAL.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/servlet-api-2.5.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/servlet-api-6.0.35.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/slf4j-api-1.7.6.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/slf4j-log4j12-1.7.6.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/snmp4j-1.10.2.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/sqljdbc4-3.0.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/substance-1.0.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/wbem-1.0.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/xfire-20050202.jar:/tools/tomcat/webapps/jbmp/WEB-INF/lib/xml-apis-1.0.b2.jar'
#echo $CLASSPATH
export DEBUG='-XX:+UnlockDiagnosticVMOptions -XX:+PrintInterpreter'
export PRINT_GC='-XX:+PrintGCDetails -Xloggc:gc.log -XX:+PrintGCDateStamps -XX:+PrintCommandLineFlags -XX:+PrintTenuringDistribution'
export GC_TYPE='-XX:+UseParallelOldGC'
export RMI='-Djava.rmi.server.hostname=192.168.8.175 -Dcom.sun.management.jmxremote.port=1090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false'
export OOM='-XX:+HeapDumpOnOutOfMemoryError'
export SIZE='-Xmx512m -Xms512m -XX:PermSize=40m -XX:MaxPermSize=40m'
export NETBEANS='-agentpath:F:/application/profiler-server-win/lib/deployed/jdk16/windows/profilerinterface.dll=F:/application/profiler-server-win/lib,5140'
#echo $PRINT_GC $GC_TYPE $RMI jetsennet.jbmp.ui.CollMgrSCFrm
#java $SIZE $PRINT_GC $GC_TYPE $RMI jetsennet.jbmp.ui.CollMgrSCFrm
java -classpath $CLASSPATH jetsennet.jbmp.ui.CollMgrSCFrm