@echo off
set CLASSPATH=.;.\classes;.\lib\activation-1.1.jar;.\lib\asm.jar;.\lib\asm-attrs.jar;.\lib\atmosphere-compat-jbossweb-0.7.2.jar;.\lib\atmosphere-compat-tomcat-0.7.2.jar;.\lib\atmosphere-compat-weblogic-0.7.2.jar;.\lib\atmosphere-ping-0.7.2.jar;.\lib\atmosphere-runtime-0.7.2.jar;.\lib\avalon-excalibur-4.1.jar;.\lib\avalon-framework-4.1.2.jar;.\lib\axiom-api-1.2.13.jar;.\lib\axiom-impl-1.2.13.jar;.\lib\axis.jar;.\lib\axis2-adb-1.6.2.jar;.\lib\axis2-adb-codegen-1.6.2.jar;.\lib\axis2-codegen-1.6.2.jar;.\lib\axis2-java2wsdl-1.6.2.jar;.\lib\axis2-kernel-1.6.2.jar;.\lib\axis2-transport-http-1.6.2.jar;.\lib\axis2-transport-local-1.6.2.jar;.\lib\c3p0-0.9.0.jar;.\lib\cglib-2.1.3.jar;.\lib\ch.ntb.usb-0.5.9.jar;.\lib\com.ibm.ws.admin.client_7.0.0.jar;.\lib\com.ibm.ws.admin.core.jar;.\lib\com.ibm.ws.orb_7.0.0.jar;.\lib\com.ibm.ws.runtime.jar;.\lib\com.ibm.ws.security.crypto.jar;.\lib\commons-attributes-api-2.1.jar;.\lib\commons-beanutils-1.7.1-20061106.jar;.\lib\commons-codec-1.3.jar;.\lib\commons-collections-3.2.jar;.\lib\commons-dbcp-1.4.jar;.\lib\commons-dbutils-1.1.jar;.\lib\commons-digester-1.8.jar;.\lib\commons-discovery-0.2.jar;.\lib\commons-fileupload-1.2.1.jar;.\lib\commons-httpclient-3.1.jar;.\lib\commons-io-1.2.jar;.\lib\commons-lang-2.4.jar;.\lib\commons-logging-1.1.1.jar;.\lib\commons-pool-1.1.jar;.\lib\dayang_ws_sc.jar;.\lib\db2jcc.jar;.\lib\db2jcc_license_cu.jar;.\lib\dom4j-1.6.1.jar;.\lib\ehcache-2.7.0.jar;.\lib\grammatica-1.5.jar;.\lib\hsqldb.jar;.\lib\httpcore-4.0.jar;.\lib\ibmjgssprovider.jar;.\lib\ibmjsseprovider2.jar;.\lib\javabase64-1.3.1.jar;.\lib\jaxen-1.1-beta-9.jar;.\lib\jaxrpc.jar;.\lib\jdom-1.0.jar;.\lib\jetsennet.bfss.jar;.\lib\jetsennet.dataaccess.jar;.\lib\jetsennet.ftsafe.jar;.\lib\jetsennet.library.jar;.\lib\JetsenSumaWS.jar;.\lib\jetty-6.1H.24.jar;.\lib\jetty-util-6.1H.24.jar;.\lib\jgroups-2.12.2.Final.jar;.\lib\jpcap.jar;.\lib\jrobin-1.5.12.jar;.\lib\json_simple-1.1.jar;.\lib\jxl-2.6.jar;.\lib\log4j-1.2.16.jar;.\lib\logkit.jar;.\lib\mail-1.4.jar;.\lib\mibble_20110105.jar;.\lib\mibble-mibs-2.9.2.jar;.\lib\mibble-parser-2.9.2.jar;.\lib\mvel2-2.0.19.jar;.\lib\mysql-connector-java-5.1.24-bin.jar;.\lib\neethi-3.0.2.jar;.\lib\ojdbc14.jar;.\lib\orai18n.jar;.\lib\poi-3.8-20120326.jar;.\lib\poi-ooxml-3.8-20120326.jar;.\lib\saaj.jar;.\lib\slf4j-api-1.7.5.jar;.\lib\slf4j-log4j12-1.7.5.jar;.\lib\snmp4j-1.10.2.jar;.\lib\sobey_ws_js.jar;.\lib\spring-1.2.6.jar;.\lib\sqljdbc4.jar;.\lib\substance.jar;.\lib\wbem.jar;.\lib\wsdl4j-1.6.1.jar;.\lib\wsdl4j-1.6.2.jar;.\lib\wstx-asl-3.2.9.jar;.\lib\xbean-spring-2.8.jar;.\lib\xfire-aegis-1.2.6.jar;.\lib\xfire-annotations-1.2.6.jar;.\lib\xfire-core-1.2.6.jar;.\lib\xfire-generator-1.2.6.jar;.\lib\xfire-java5-1.2.6.jar;.\lib\xfire-jaxb2-1.2.6.jar;.\lib\xfire-jaxws-1.2.6.jar;.\lib\xfire-jsr181-api-1.0-M1.jar;.\lib\xfire-spring-1.2.6.jar;.\lib\xfire-ws-security-1.2.6.jar;.\lib\xfire-xmlbeans-1.2.6.jar;.\lib\XmlSchema-1.4.7.jar 

echo %CLASSPATH%
set DEBUG=-XX:+UnlockDiagnosticVMOptions -XX:+PrintInterpreter
set PRINT_GC=-XX:+PrintGCDetails -Xloggc:gc.log -XX:+PrintGCDateStamps -XX:+PrintCommandLineFlags -XX:+PrintTenuringDistribution
set GC_TYPE=-XX:+UseParallelOldGC
set RMI=-Djava.rmi.server.hostname=192.168.8.171 -Dcom.sun.management.jmxremote.port=1090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
set OOM=-XX:+HeapDumpOnOutOfMemoryError
set SIZE=-Xmx512m -Xms512m -XX:PermSize=40m -XX:MaxPermSize=40m
set NETBEANS=-agentpath:F:\application\profiler-server-win\lib\deployed\jdk16\windows\profilerinterface.dll=F:\application\profiler-server-win\lib,5140
echo %PRINT_GC% %GC_TYPE% %RMI% jetsennet.jbmp.ui.CollMgrSCFrm
java %SIZE% %PRINT_GC% %GC_TYPE% %RMI% %NETBEANS% jetsennet.jbmp.ui.CollMgrSCFrm